// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/shipment.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Driver        string                 `protobuf:"bytes,3,opt,name=driver,proto3" json:"driver,omitempty"`
	Unit          string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	Cost          float64                `protobuf:"fixed64,5,opt,name=cost,proto3" json:"cost,omitempty"`
	DriverRevenue float64                `protobuf:"fixed64,6,opt,name=driver_revenue,json=driverRevenue,proto3" json:"driver_revenue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShipmentRequest) Reset() {
	*x = CreateShipmentRequest{}
	mi := &file_proto_shipment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentRequest) ProtoMessage() {}

func (x *CreateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentRequest.ProtoReflect.Descriptor instead.
func (*CreateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_shipment_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShipmentRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *CreateShipmentRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *CreateShipmentRequest) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *CreateShipmentRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *CreateShipmentRequest) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *CreateShipmentRequest) GetDriverRevenue() float64 {
	if x != nil {
		return x.DriverRevenue
	}
	return 0
}

type CreateShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reference     string                 `protobuf:"bytes,2,opt,name=reference,proto3" json:"reference,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShipmentResponse) Reset() {
	*x = CreateShipmentResponse{}
	mi := &file_proto_shipment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentResponse) ProtoMessage() {}

func (x *CreateShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentResponse.ProtoReflect.Descriptor instead.
func (*CreateShipmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_shipment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShipmentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateShipmentResponse) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *CreateShipmentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentRequest) Reset() {
	*x = GetShipmentRequest{}
	mi := &file_proto_shipment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentRequest) ProtoMessage() {}

func (x *GetShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_shipment_proto_rawDescGZIP(), []int{2}
}

func (x *GetShipmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Reference     string                 `protobuf:"bytes,3,opt,name=reference,proto3" json:"reference,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Origin        string                 `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   string                 `protobuf:"bytes,6,opt,name=destination,proto3" json:"destination,omitempty"`
	Unit          string                 `protobuf:"bytes,7,opt,name=unit,proto3" json:"unit,omitempty"`
	Cost          float64                `protobuf:"fixed64,8,opt,name=cost,proto3" json:"cost,omitempty"`
	Driver        string                 `protobuf:"bytes,9,opt,name=driver,proto3" json:"driver,omitempty"`
	DriverRevenue float64                `protobuf:"fixed64,10,opt,name=driver_revenue,json=driverRevenue,proto3" json:"driver_revenue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentResponse) Reset() {
	*x = GetShipmentResponse{}
	mi := &file_proto_shipment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentResponse) ProtoMessage() {}

func (x *GetShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentResponse.ProtoReflect.Descriptor instead.
func (*GetShipmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_shipment_proto_rawDescGZIP(), []int{3}
}

func (x *GetShipmentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetShipmentResponse) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *GetShipmentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetShipmentResponse) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *GetShipmentResponse) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *GetShipmentResponse) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *GetShipmentResponse) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *GetShipmentResponse) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *GetShipmentResponse) GetDriverRevenue() float64 {
	if x != nil {
		return x.DriverRevenue
	}
	return 0
}

type AddShipmentEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddShipmentEventRequest) Reset() {
	*x = AddShipmentEventRequest{}
	mi := &file_proto_shipment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddShipmentEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShipmentEventRequest) ProtoMessage() {}

func (x *AddShipmentEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShipmentEventRequest.ProtoReflect.Descriptor instead.
func (*AddShipmentEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_shipment_proto_rawDescGZIP(), []int{4}
}

func (x *AddShipmentEventRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *AddShipmentEventRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AddShipmentEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddShipmentEventResponse) Reset() {
	*x = AddShipmentEventResponse{}
	mi := &file_proto_shipment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddShipmentEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShipmentEventResponse) ProtoMessage() {}

func (x *AddShipmentEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShipmentEventResponse.ProtoReflect.Descriptor instead.
func (*AddShipmentEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_shipment_proto_rawDescGZIP(), []int{5}
}

func (x *AddShipmentEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddShipmentEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetShipmentEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentEventsRequest) Reset() {
	*x = GetShipmentEventsRequest{}
	mi := &file_proto_shipment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentEventsRequest) ProtoMessage() {}

func (x *GetShipmentEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentEventsRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shipment_proto_rawDescGZIP(), []int{6}
}

func (x *GetShipmentEventsRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

type GetShipmentEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*ShipmentEvent       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentEventsResponse) Reset() {
	*x = GetShipmentEventsResponse{}
	mi := &file_proto_shipment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentEventsResponse) ProtoMessage() {}

func (x *GetShipmentEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentEventsResponse.ProtoReflect.Descriptor instead.
func (*GetShipmentEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_shipment_proto_rawDescGZIP(), []int{7}
}

func (x *GetShipmentEventsResponse) GetEvents() []*ShipmentEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ShipmentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Time          string                 `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipmentEvent) Reset() {
	*x = ShipmentEvent{}
	mi := &file_proto_shipment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentEvent) ProtoMessage() {}

func (x *ShipmentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentEvent.ProtoReflect.Descriptor instead.
func (*ShipmentEvent) Descriptor() ([]byte, []int) {
	return file_proto_shipment_proto_rawDescGZIP(), []int{8}
}

func (x *ShipmentEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ShipmentEvent) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

var File_proto_shipment_proto protoreflect.FileDescriptor

const file_proto_shipment_proto_rawDesc = "" +
	"\n" +
	"\x14proto/shipment.proto\x12\bshipment\"\xb8\x01\n" +
	"\x15CreateShipmentRequest\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x16\n" +
	"\x06driver\x18\x03 \x01(\tR\x06driver\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\x12\x12\n" +
	"\x04cost\x18\x05 \x01(\x01R\x04cost\x12%\n" +
	"\x0edriver_revenue\x18\x06 \x01(\x01R\rdriverRevenue\"^\n" +
	"\x16CreateShipmentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\treference\x18\x02 \x01(\tR\treference\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"$\n" +
	"\x12GetShipmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xfc\x01\n" +
	"\x13GetShipmentResponse\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1c\n" +
	"\treference\x18\x03 \x01(\tR\treference\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x16\n" +
	"\x06origin\x18\x05 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x06 \x01(\tR\vdestination\x12\x12\n" +
	"\x04unit\x18\a \x01(\tR\x04unit\x12\x12\n" +
	"\x04cost\x18\b \x01(\x01R\x04cost\x12\x16\n" +
	"\x06driver\x18\t \x01(\tR\x06driver\x12%\n" +
	"\x0edriver_revenue\x18\n" +
	" \x01(\x01R\rdriverRevenue\"R\n" +
	"\x17AddShipmentEventRequest\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"N\n" +
	"\x18AddShipmentEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\";\n" +
	"\x18GetShipmentEventsRequest\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\"L\n" +
	"\x19GetShipmentEventsResponse\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.shipment.ShipmentEventR\x06events\";\n" +
	"\rShipmentEvent\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04time\x18\x02 \x01(\tR\x04time2\xeb\x02\n" +
	"\x0fShipmentService\x12S\n" +
	"\x0eCreateShipment\x12\x1f.shipment.CreateShipmentRequest\x1a .shipment.CreateShipmentResponse\x12J\n" +
	"\vGetShipment\x12\x1c.shipment.GetShipmentRequest\x1a\x1d.shipment.GetShipmentResponse\x12Y\n" +
	"\x10AddShipmentEvent\x12!.shipment.AddShipmentEventRequest\x1a\".shipment.AddShipmentEventResponse\x12\\\n" +
	"\x11GetShipmentEvents\x12\".shipment.GetShipmentEventsRequest\x1a#.shipment.GetShipmentEventsResponseB0Z.github.com/Aiya594/shipment-microservice/protob\x06proto3"

var (
	file_proto_shipment_proto_rawDescOnce sync.Once
	file_proto_shipment_proto_rawDescData []byte
)

func file_proto_shipment_proto_rawDescGZIP() []byte {
	file_proto_shipment_proto_rawDescOnce.Do(func() {
		file_proto_shipment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shipment_proto_rawDesc), len(file_proto_shipment_proto_rawDesc)))
	})
	return file_proto_shipment_proto_rawDescData
}

var file_proto_shipment_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_shipment_proto_goTypes = []any{
	(*CreateShipmentRequest)(nil),     // 0: shipment.CreateShipmentRequest
	(*CreateShipmentResponse)(nil),    // 1: shipment.CreateShipmentResponse
	(*GetShipmentRequest)(nil),        // 2: shipment.GetShipmentRequest
	(*GetShipmentResponse)(nil),       // 3: shipment.GetShipmentResponse
	(*AddShipmentEventRequest)(nil),   // 4: shipment.AddShipmentEventRequest
	(*AddShipmentEventResponse)(nil),  // 5: shipment.AddShipmentEventResponse
	(*GetShipmentEventsRequest)(nil),  // 6: shipment.GetShipmentEventsRequest
	(*GetShipmentEventsResponse)(nil), // 7: shipment.GetShipmentEventsResponse
	(*ShipmentEvent)(nil),             // 8: shipment.ShipmentEvent
}
var file_proto_shipment_proto_depIdxs = []int32{
	8, // 0: shipment.GetShipmentEventsResponse.events:type_name -> shipment.ShipmentEvent
	0, // 1: shipment.ShipmentService.CreateShipment:input_type -> shipment.CreateShipmentRequest
	2, // 2: shipment.ShipmentService.GetShipment:input_type -> shipment.GetShipmentRequest
	4, // 3: shipment.ShipmentService.AddShipmentEvent:input_type -> shipment.AddShipmentEventRequest
	6, // 4: shipment.ShipmentService.GetShipmentEvents:input_type -> shipment.GetShipmentEventsRequest
	1, // 5: shipment.ShipmentService.CreateShipment:output_type -> shipment.CreateShipmentResponse
	3, // 6: shipment.ShipmentService.GetShipment:output_type -> shipment.GetShipmentResponse
	5, // 7: shipment.ShipmentService.AddShipmentEvent:output_type -> shipment.AddShipmentEventResponse
	7, // 8: shipment.ShipmentService.GetShipmentEvents:output_type -> shipment.GetShipmentEventsResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_shipment_proto_init() }
func file_proto_shipment_proto_init() {
	if File_proto_shipment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shipment_proto_rawDesc), len(file_proto_shipment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shipment_proto_goTypes,
		DependencyIndexes: file_proto_shipment_proto_depIdxs,
		MessageInfos:      file_proto_shipment_proto_msgTypes,
	}.Build()
	File_proto_shipment_proto = out.File
	file_proto_shipment_proto_goTypes = nil
	file_proto_shipment_proto_depIdxs = nil
}
